name: auto merge branche


- name: Merge pull requests
       uses: pascalgn/automerge-action@v0.9.0
       env:
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "auto merging"
