name: auto-merge

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - edited
      - ready_for_review
      - reopened
      - unlocked
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # auto merge job
  automerge-draft:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.9.0
        env:
          GITHUB_TOKEN: '${{ secrets.AUTO_MERGE_TOKEN }}'
          MERGE_COMMIT_MESSAGE: 'pull-request-title-and-description'
          MERGE_LABELS: 'netlify-cms/draft'
          MERGE_DELETE_BRANCH: true
  automerge-pending_publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.9.0
        env:
          GITHUB_TOKEN: '${{ secrets.AUTO_MERGE_TOKEN }}'
          MERGE_COMMIT_MESSAGE: 'pull-request-title-and-description'
          MERGE_LABELS: 'netlify-cms/pending_publish'
          MERGE_DELETE_BRANCH: true
